In [18]:
import numpy as np
def change(A):
    A[0, 0] = 1
A = np.zeros((1, 3))
change(A)
A

array([[1., 0., 0.]])

In [14]:
A ="[[ 0  0  0  0  0  0  0  0]\
  [ 0  1  0  0  0  0  1  0]\
  [ 0  0  1  0  0  1  0  0]\
  [ 0  0  0  1  1  0  0  0]\
  [ 0  0  0  -1  -1  0  0  0]\
  [ 0  0  -1  0  0  -1  0  0]\
  [ 0  -1  0  0  0  0  -1  0]\
  [ 0  0  0  0  0  0  0  0]]"


A = A.replace("  ",",")
A

'[[ 0,0,0,0,0,0,0,0],[ 0,1,0,0,0,0,1,0],[ 0,0,1,0,0,1,0,0],[ 0,0,0,1,1,0,0,0],[ 0,0,0,-1,-1,0,0,0],[ 0,0,-1,0,0,-1,0,0],[ 0,-1,0,0,0,0,-1,0],[ 0,0,0,0,0,0,0,0]]'