## Practice




In [85]:
import numpy as np
from numpy.random import default_rng
from random import random

1. Create a 10*10 ndarray object, and the matrix boundary value is 1, and the rest are 0.

In [86]:
# 1
A = np.ones((10,10))
A[1:9,1:9] = 0
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

2. Create a 5*5 matrix with each row being 0 to 4

In [87]:
# 2
A = np.zeros((5, 5),'int16')
A[:] = [0,1,2,3,4]
A

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int16)

In [88]:
#This is test case
A = np.zeros((5,5),'int16')
for row in A:
  row = np.arange(5)
A

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

3. Create an 8*8 matrix and fill it with a checkerboard pattern, like [[0,1],[1,0]])

In [89]:
# 3
A = np.array([[0,1],[1,0]],'float')
np.tile(A,(4,4))

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

4. output all the odd numbers in the array  
   Example:  
   in:    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
   out:   array([1, 3, 5, 7, 9])  

In [90]:
#4
A = np.zeros(8)
A = np.random.randint(10,size=8)
print(A)
A[A / 2 != A // 2]

[5 5 0 2 9 5 3 4]


array([5, 5, 9, 5, 3])

5. Normalize a 5x5 random matrix 

In [91]:
# 5
A = default_rng(1).random((5,5))
print (A)

std = A.std()
print("std: ",std)
mean = A.mean()
print ("Mean: ",mean)
A -= mean
A /= std
A

[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]
 [0.42332645 0.82770259 0.40919914 0.54959369 0.02755911]
 [0.75351311 0.53814331 0.32973172 0.7884287  0.30319483]
 [0.45349789 0.1340417  0.40311299 0.20345524 0.26231334]
 [0.75036467 0.28040876 0.48519097 0.9807372  0.96165719]]
std:  0.28094811772104267
Mean:  0.5092839374756314


array([[ 0.00903258,  1.57032467, -1.29961477,  1.56386707, -0.70280765],
       [-0.30595503,  1.13337174, -0.35623944,  0.14347756, -1.7146398 ],
       [ 0.86930346,  0.10272137, -0.63909387,  0.99358119, -0.73354863],
       [-0.19856352, -1.33562824, -0.37790234, -1.08855934, -0.87906123],
       [ 0.85809699, -0.81465283, -0.08575592,  1.67807945,  1.61016653]])

6. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates.

In [92]:
# 6
print("X,Y:")
A = default_rng().random((2,10))
A = np.array([[0,1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9,10]])
B = np.zeros((2,10))
B[0] = (A[0] ** 2 + A[1] ** 2) ** (1/2)
B[1] = np.arctan2(A[1],A[0]) * 180 / np.pi
B
print("R:")
print(B[1])
print("T")
print(B[0])

X,Y:
R:
[90.         63.43494882 56.30993247 53.13010235 51.34019175 50.19442891
 49.39870535 48.81407483 48.36646066 48.0127875 ]
T
[ 1.          2.23606798  3.60555128  5.          6.40312424  7.81024968
  9.21954446 10.63014581 12.04159458 13.45362405]


7. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [98]:
# 7
A = np.array([1,2,3,4,5])
B = np.zeros(len(A) * 4 - 3)
C = B[0:len(B):4]
C[:] = A[:]
B


array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.,
       0., 0., 0., 6.])

8. What are the result of the following expressions?

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1 

(hint1:nan means not a number 
hint2:0.1(10) == 0.0001100110011001100110011001100110011001100110011...(2))
First guess a result, then print the result, and finally find why

In [94]:
# 8
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1 )
print(3 * 0.1) #浮点精度问题

nan
False
False
nan
True
False
0.30000000000000004


9. What are the result of the following expressions? (Hint: the type of pn.nan is float)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)


First guess a result, then print the result, and finally find why 

In [95]:
# 9
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-2.14748365e+09]


C:\Users\lenovo\AppData\Local\Temp\ipykernel_21388\2007467555.py:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\lenovo\AppData\Local\Temp\ipykernel_21388\2007467555.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
